//! Shared conformance suite `canonical` (v1.2.0), generated by the Python
//! reference (genesismesh/conformance/generate_vectors.py canonical) and
//! copied unchanged: the field registry of signed records and the fields
//! every verifier refuses.

use genesis_mesh_sdk::strict::{is_known_entry_kind, unknown_fields, CANONICAL_REGISTRY};
use genesis_mesh_sdk::verify::{
    verify_boundary_decision, verify_evidence_events, VerifyDecisionOptions, VerifyEvidenceOptions,
};
use serde_json::{json, Value};

fn suite() -> Value {
    serde_json::from_str(include_str!("fixtures/canonical.json")).unwrap()
}

#[test]
fn embeds_the_registry_of_the_suite() {
    assert_eq!(
        *CANONICAL_REGISTRY,
        suite()["registry"],
        "run `python scripts/sync_canonical_registry.py` after copying a new suite"
    );
}

#[test]
fn every_vector_gives_the_reference_outcome() {
    let suite = suite();
    let vectors = suite["vectors"].as_array().unwrap();
    assert!(vectors.len() >= 60);
    for v in vectors {
        let got = match v["kind"].as_str().unwrap() {
            "unknown_fields" => {
                let mut found = unknown_fields(v["model"].as_str().unwrap(), &v["record"]);
                found.sort();
                json!({ "unknown_fields": found })
            }
            "entry_kind" => {
                json!({ "known": is_known_entry_kind(v["entry_kind"].as_str().unwrap()) })
            }
            other => panic!("unknown vector kind {other}"),
        };
        assert_eq!(got, v["expected"], "{}", v["id"]);
    }
}

fn record(model: &str) -> Value {
    suite()["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| {
            v["kind"] == "unknown_fields"
                && v["model"] == model
                && v["expected"]["unknown_fields"] == json!([])
        })
        .map(|v| v["record"].clone())
        .unwrap()
}

#[test]
fn a_decision_with_a_field_from_a_later_release_is_refused_by_name() {
    let mut decision = record("BoundaryDecision");
    decision["risk_tier"] = json!("high");
    let result = verify_boundary_decision(&decision, &VerifyDecisionOptions::default());
    assert!(!result.accepted);
    assert_eq!(result.reason, "unknown_field");

    let mut policy = record("BoundaryPolicy");
    policy["x"] = json!(1);
    let options = VerifyDecisionOptions {
        expected_policies: Some(vec![policy]),
        ..Default::default()
    };
    assert_eq!(
        verify_boundary_decision(&record("BoundaryDecision"), &options).reason,
        "unknown_field"
    );
}

#[test]
fn an_export_names_unknown_kinds_and_fields() {
    let event = |kind: &str, seq: i64| {
        json!({
            "schema": "gm.evidence.event", "schema_version": 1, "entry_digest": "x", "payload": { "x": 1 },
            "entry": { "store_sequence": seq, "entry_kind": kind, "recorded_at": "2026-01-01T00:00:00Z",
                "payload_digest": "p", "prev_entry_digest": null, "decision_id": null, "context_id": null,
                "vendor_id": null, "attestation_id": null, "capability": null, "outcome": null,
                "evidence_id": null, "executor_sovereign_id": null, "exec_sequence_no": null,
                "resource_id": null, "resource_action": null, "resource_sequence": null }
        })
    };
    let events = [event("observation", 1), event("justification", 2)];
    let options = VerifyEvidenceOptions {
        na_public_keys: vec![],
        executor_keys: vec![],
        contiguous: true,
        checkpoint: None,
    };
    let result = verify_evidence_events(events.iter(), &options);
    let reasons: Vec<String> = result
        .failures
        .iter()
        .map(|f| format!("{}:{}", f.store_sequence.unwrap_or_default(), f.reason))
        .collect();
    assert!(
        reasons.contains(&"1:unknown_entry_kind".to_owned()),
        "{reasons:?}"
    );
    assert!(
        reasons.contains(&"2:unknown_field".to_owned()),
        "{reasons:?}"
    );
}
