//! Shared conformance suite `canonical` (v1.2.0), generated by the Python
//! reference (genesismesh/conformance/generate_vectors.py canonical) and copied
//! unchanged: input every implementation reads alike or refuses by reason, and
//! the canonical form of records.

use chrono::{DateTime, Utc};
use genesis_mesh_sdk::{
    canonical_json, parse_strict_json,
    strict::{canonical_timestamp, non_canonical_timestamps},
    verify::{parse_export_lines, verify_boundary_decision, VerifyDecisionOptions},
    GenesisMeshError,
};
use serde_json::{json, Value};

fn suite() -> Value {
    serde_json::from_str(include_str!("fixtures/canonical.json")).unwrap()
}

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_owned())
        .collect()
}

#[test]
fn every_vector_gives_the_reference_outcome() {
    let suite = suite();
    let vectors = suite["vectors"].as_array().unwrap();
    assert!(vectors.len() >= 70);
    for v in vectors {
        let input = &v["input"];
        let got = match v["kind"].as_str().unwrap() {
            "json" => match parse_strict_json(input.as_str().unwrap()) {
                Ok(value) => json!({ "canonical": canonical_json(&value).unwrap() }),
                Err(GenesisMeshError::StrictJson { reason, .. }) => json!({ "refused": reason }),
                Err(other) => panic!("{}: {other}", v["id"]),
            },
            "timestamp" => json!({ "canonical": canonical_timestamp(input.as_str().unwrap()) }),
            "verify_decision" => {
                let now: DateTime<Utc> = input["now"].as_str().unwrap().parse().unwrap();
                let options = VerifyDecisionOptions {
                    operator_public_keys: strings(&input["operator_public_keys"]),
                    now: Some(now),
                    ..Default::default()
                };
                let r = verify_boundary_decision(&input["decision"], &options);
                json!({ "accepted": r.accepted, "reason": r.reason })
            }
            // This crate has no agreement or data-usage verifier.
            "verify_agreement" | "verify_intent" => continue,
            other => panic!("unknown vector kind {other}"),
        };
        assert_eq!(got, v["expected"], "{}", v["id"]);
    }
}

#[test]
fn names_timestamp_paths_at_any_depth() {
    let suite = suite();
    let agreement = suite["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["id"] == "verify-agreement-signed-non-canonical-timestamp")
        .unwrap();
    assert_eq!(
        non_canonical_timestamps("AgreementRecord", &agreement["input"]["agreement"]),
        ["agreed_terms.valid_from"]
    );
}

#[test]
fn export_lines_are_read_strictly() {
    let err = parse_export_lines(r#"{"schema":"gm.evidence.event","schema":"x"}"#).unwrap_err();
    assert_eq!(err.code(), "duplicate_key");
    // Only JSON whitespace is stripped around a line.
    assert!(parse_export_lines(" \t\r\n").unwrap().is_empty());
    assert_eq!(
        parse_export_lines("\u{a0}{}").unwrap_err().code(),
        "invalid_json"
    );
}

#[test]
fn long_non_ascii_strings_are_read_in_linear_time() {
    let text = format!("[\"{}\"]", "\u{e9}".repeat(1_000_000));
    let started = std::time::Instant::now();
    parse_strict_json(&text).unwrap();
    assert!(started.elapsed() < std::time::Duration::from_secs(5));
}
