//! Shared conformance suite `field_registry` (v1.2.0), generated by the Python
//! reference (genesismesh/conformance/generate_vectors.py field_registry) and
//! copied unchanged: the field registry of signed records and the fields
//! every verifier refuses.

use chrono::{DateTime, Utc};
use genesis_mesh_sdk::canonical::{
    CHECKPOINT_OMITTED_WHEN_ABSENT, DECISION_OMITTED_WHEN_ABSENT, ENVELOPE_OMITTED_WHEN_ABSENT,
    RESOURCE_CHAIN_FIELDS,
};
use genesis_mesh_sdk::strict::{
    embedded_registry, is_known_entry_kind, registry_list, unknown_fields,
};
use genesis_mesh_sdk::verify::{
    parse_export_lines, verify_boundary_decision, verify_evidence_events, VerifyDecisionOptions,
    VerifyEvidenceOptions,
};
use serde_json::{json, Value};

fn suite() -> Value {
    serde_json::from_str(include_str!("fixtures/field_registry.json")).unwrap()
}

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_owned())
        .collect()
}

fn no_keys() -> VerifyEvidenceOptions {
    VerifyEvidenceOptions {
        na_public_keys: vec![],
        executor_keys: vec![],
        contiguous: true,
        checkpoint: None,
    }
}

#[test]
fn embeds_the_registry_of_the_suite() {
    assert_eq!(
        *embedded_registry(),
        suite()["registry"],
        "run `python scripts/sync_canonical_registry.py` after copying a new suite"
    );
}

#[test]
fn keeps_this_crates_canonical_rules_equal_to_the_registrys() {
    assert_eq!(
        RESOURCE_CHAIN_FIELDS.to_vec(),
        registry_list("ExecutionEvidence", "omit_when_none")
    );
    assert_eq!(
        DECISION_OMITTED_WHEN_ABSENT.to_vec(),
        registry_list("BoundaryDecision", "omit_when_none")
    );
    // v1.3.0: envelope and checkpoint fields left out when absent.
    assert_eq!(
        ENVELOPE_OMITTED_WHEN_ABSENT.to_vec(),
        registry_list("EvidenceStoreEntry", "omit_when_none")
    );
    assert_eq!(
        CHECKPOINT_OMITTED_WHEN_ABSENT.to_vec(),
        registry_list("RetentionCheckpoint", "omit_when_none")
    );
}

#[test]
fn every_vector_gives_the_reference_outcome() {
    let suite = suite();
    let vectors = suite["vectors"].as_array().unwrap();
    assert!(vectors.len() >= 70);
    for v in vectors {
        let input = &v["input"];
        let got = match v["kind"].as_str().unwrap() {
            "unknown_fields" => json!({
                "unknown_fields": unknown_fields(v["model"].as_str().unwrap(), &v["record"])
            }),
            "entry_kind" => {
                json!({ "known": is_known_entry_kind(v["entry_kind"].as_str().unwrap()) })
            }
            "verify_decision" => {
                let now: DateTime<Utc> = input["now"].as_str().unwrap().parse().unwrap();
                let options = VerifyDecisionOptions {
                    operator_public_keys: strings(&input["operator_public_keys"]),
                    now: Some(now),
                    ..Default::default()
                };
                let r = verify_boundary_decision(&input["decision"], &options);
                json!({ "accepted": r.accepted, "reason": r.reason })
            }
            // This crate has no agreement verifier.
            "verify_agreement" => continue,
            "export" => {
                let events = parse_export_lines(input["lines"].as_str().unwrap()).unwrap();
                // v1.3.0: a vector may name the NA keys its records are signed by.
                let options = VerifyEvidenceOptions {
                    na_public_keys: input.get("na_public_keys").map(strings).unwrap_or_default(),
                    ..no_keys()
                };
                let result = verify_evidence_events(events.iter(), &options);
                let failures: Vec<Value> = result
                    .failures
                    .iter()
                    .map(|f| json!({ "store_sequence": f.store_sequence, "reason": f.reason }))
                    .collect();
                json!({ "failures": failures })
            }
            other => panic!("unknown vector kind {other}"),
        };
        assert_eq!(got, v["expected"], "{}", v["id"]);
    }
}

#[test]
fn an_expected_policy_with_an_unknown_field_is_refused_by_name() {
    let suite = suite();
    let newer = suite["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["id"] == "verify-decision-newer-signed-field")
        .unwrap()["input"]
        .clone();
    let now: DateTime<Utc> = newer["now"].as_str().unwrap().parse().unwrap();
    let policy = suite["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["id"] == "boundarypolicy-top")
        .unwrap()["record"]
        .clone();
    let options = VerifyDecisionOptions {
        operator_public_keys: strings(&newer["operator_public_keys"]),
        now: Some(now),
        expected_policies: Some(vec![policy]),
        ..Default::default()
    };
    assert_eq!(
        verify_boundary_decision(&newer["decision"], &options).reason,
        "unknown_field"
    );
}
