//! Changes made outside the controlled path (Genesis Mesh 1.3.0): the shared
//! conformance suite `out_of_band`, generated by the Python reference
//! (genesismesh/conformance/generate_vectors.py) and copied unchanged, and
//! the records this crate signs.

use std::collections::BTreeSet;

use base64::{engine::general_purpose::STANDARD, Engine as _};
use chrono::{DateTime, Utc};
use ed25519_dalek::SigningKey;
use genesis_mesh_sdk::{
    canonical::{
        checkpoint_canonical, entry_digest, out_of_band_canonical, out_of_band_digest,
        payload_digest,
    },
    canonical_digest, json, observation_from_finding, public_key_from_seed, sign_canonical,
    verify::{
        parse_export_lines, verify_evidence_events, verify_out_of_band_record,
        VerifyEvidenceOptions,
    },
    BreakGlassInput, EvaluationFailure, ExecutionRecorder, FindingObservationOptions,
    GenesisMeshError, ObservationInput, ObservationRecorder, Value,
};
use sha2::{Digest, Sha256};

fn suite() -> Value {
    serde_json::from_str(include_str!("fixtures/out_of_band.json")).unwrap()
}

fn strings(value: &Value) -> Vec<String> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_owned())
        .collect()
}

const COUNTS: [&str; 4] = ["observations", "break_glass", "judgements", "quarantined"];

/// The `time_bounds` and `policy_history` vectors are the NA's own rules: an
/// SDK neither admits nor judges records, so they are not run here.
#[test]
fn every_vector_gives_the_reference_outcome() {
    let suite = suite();
    assert_eq!(suite["suite"], "out_of_band");
    let mut ran = 0;
    for v in suite["vectors"].as_array().unwrap() {
        let got = match v["kind"].as_str().unwrap() {
            "verify_export" => {
                let input = &v["input"];
                let events = parse_export_lines(input["lines"].as_str().unwrap()).unwrap();
                let options = VerifyEvidenceOptions {
                    contiguous: input["contiguous"].as_bool().unwrap(),
                    ..VerifyEvidenceOptions::new(
                        strings(&input["na_public_keys"]),
                        input["executor_keys"].as_array().unwrap().clone(),
                    )
                };
                let result = verify_evidence_events(&events, &options);
                // Deduplicated and sorted, as the reference runner reports them.
                let found: BTreeSet<(Option<i64>, String)> = result
                    .failures
                    .iter()
                    .map(|f| (f.store_sequence, f.reason.clone()))
                    .collect();
                let mut found: Vec<_> = found.into_iter().collect();
                found.sort_by(|a, b| (a.0.unwrap_or(0), &a.1).cmp(&(b.0.unwrap_or(0), &b.1)));
                let failures: Vec<Value> = found
                    .into_iter()
                    .map(|(seq, reason)| json!({"store_sequence": seq, "reason": reason}))
                    .collect();
                // The counts as serialized: present when nonzero.
                let serialized = serde_json::to_value(&result).unwrap();
                let counts: serde_json::Map<String, Value> = COUNTS
                    .iter()
                    .filter_map(|k| Some((k.to_string(), serialized.get(*k)?.clone())))
                    .collect();
                json!({"verified": result.verified, "failures": failures, "counts": counts})
            }
            "canonical_form" => json!({
                "canonical": out_of_band_canonical(&v["record"]).unwrap(),
                "digest": out_of_band_digest(&v["record"]).unwrap(),
            }),
            "verify_record" => json!({
                "valid": verify_out_of_band_record(
                    &v["record"],
                    &[v["public_key"].as_str().unwrap().to_owned()]
                )
            }),
            "time_bounds" | "policy_history" => continue,
            other => panic!("unknown vector kind {other}"),
        };
        assert_eq!(got, v["expected"], "{}", v["id"]);
        ran += 1;
    }
    assert_eq!(ran, 19);
}

#[test]
fn a_record_with_an_unknown_signed_field_does_not_verify() {
    let suite = suite();
    let vector = suite["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["id"] == "signature-judgement-na-key")
        .unwrap();
    let key = [vector["public_key"].as_str().unwrap().to_owned()];
    assert!(verify_out_of_band_record(&vector["record"], &key));
    let mut tampered = vector["record"].clone();
    tampered["verdict"] = json!("allow");
    assert!(!verify_out_of_band_record(&tampered, &key));
    // A record of no known kind.
    let mut unknown = vector["record"].clone();
    unknown.as_object_mut().unwrap().remove("judgement_id");
    assert!(!verify_out_of_band_record(&unknown, &key));
}

fn seed(byte: u8) -> String {
    STANDARD.encode([byte; 32])
}

fn at(value: &str) -> DateTime<Utc> {
    value.parse().unwrap()
}

fn observer() -> ObservationRecorder {
    ObservationRecorder::new("cloud-observer", "observer-1", &seed(11)).unwrap()
}

fn observation(resource: &str, event: &str) -> ObservationInput {
    ObservationInput {
        resource_id: resource.into(),
        action: "rotate".into(),
        capability: "secret.rotate".into(),
        changed_at: Some(at("2026-01-01T00:01:00Z")),
        observed_at: Some(at("2026-01-01T00:02:00Z")),
        source: "cloud-activity-log".into(),
        source_event_id: event.into(),
        metadata: Some(json!({"lifetime_days": 30})),
        ..ObservationInput::default()
    }
}

#[test]
fn an_observation_signs_every_field_but_the_signature_and_leaves_absent_fields_out() {
    let record = observer()
        .record(observation("kv:prod/api-key", "event-1"))
        .unwrap();
    assert_eq!(record["changed_at"], "2026-01-01T00:01:00Z");
    assert_eq!(record["observer_sovereign_id"], "cloud-observer");
    for absent in ["version_id", "changed_not_before", "actor"] {
        assert!(record.get(absent).is_none(), "{absent}");
    }
    assert_eq!(record["signature"]["key_id"], "observer-1");
    let key = [public_key_from_seed(&seed(11)).unwrap()];
    assert!(verify_out_of_band_record(&record, &key));
    let mut changed = record.clone();
    changed["action"] = json!("delete");
    assert!(!verify_out_of_band_record(&changed, &key));
}

fn refusal(err: GenesisMeshError) -> String {
    assert!(
        matches!(err, GenesisMeshError::OutOfBandRecord { .. }),
        "{err}"
    );
    err.code().to_owned()
}

#[test]
fn an_observation_needs_one_change_time_and_no_secret_material() {
    let recorder = observer();
    let none = ObservationInput {
        changed_at: None,
        ..observation("kv:prod/api-key", "e")
    };
    assert_eq!(
        refusal(recorder.record(none.clone()).unwrap_err()),
        "observation_malformed"
    );
    let both = ObservationInput {
        changed_not_before: Some(Utc::now()),
        changed_not_after: Some(Utc::now()),
        ..observation("kv:prod/api-key", "e")
    };
    let err = recorder.record(both).unwrap_err();
    assert!(err.to_string().contains("not both"), "{err}");
    let half = ObservationInput {
        changed_not_before: Some(Utc::now()),
        ..none.clone()
    };
    assert_eq!(
        refusal(recorder.record(half).unwrap_err()),
        "observation_malformed"
    );
    let backwards = ObservationInput {
        changed_not_before: Some(at("2026-01-01T01:00:00Z")),
        changed_not_after: Some(at("2026-01-01T00:00:00Z")),
        ..none
    };
    assert_eq!(
        refusal(recorder.record(backwards).unwrap_err()),
        "observation_malformed"
    );
    let secret = ObservationInput {
        metadata: Some(json!({"password": "hunter2"})),
        ..observation("kv:prod/api-key", "e")
    };
    assert_eq!(
        refusal(recorder.record(secret).unwrap_err()),
        "observation_secret_material"
    );
}

#[test]
fn a_reconciliation_finding_becomes_a_windowed_observation_once_per_scan() {
    let finding = json!({
        "resource_id": "kv:prod/api-key", "status": "drifted",
        "detail": "cloud version 3, governed version 2",
        "observed": {"resource_id": "kv:prod/api-key", "exists": true, "version": "3",
                     "metadata": {"vault": "prod"}},
        "recorded": null,
    });
    let options = FindingObservationOptions::new(
        "secret.rotate",
        at("2026-01-01T00:00:00Z"),
        at("2026-01-01T01:00:00Z"),
    );
    let input = observation_from_finding(&finding, &options).unwrap();
    assert_eq!(input.action, "update");
    assert_eq!(input.changed_not_before, Some(options.previous_scan_at));
    assert_eq!(input.changed_not_after, Some(options.scanned_at));
    assert_eq!(input.observed_at, Some(options.scanned_at));
    assert_eq!(input.version_id.as_deref(), Some("3"));
    assert_eq!(input.source, "reconciliation");
    assert_eq!(
        input.metadata,
        Some(json!({"status": "drifted", "vault": "prod"}))
    );
    // The scan, the resource and the status, as every SDK names the event.
    let event = "2026-01-01T01:00:00Z\u{0}kv:prod/api-key\u{0}drifted";
    let digest: String = Sha256::digest(event.as_bytes())
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    assert_eq!(input.source_event_id, digest);
    assert_eq!(
        observation_from_finding(&finding, &options)
            .unwrap()
            .source_event_id,
        input.source_event_id
    );
    for (status, action) in [
        ("unmanaged", Some("create")),
        ("present_after_revoke", Some("update")),
        ("missing", Some("delete")),
        ("in_sync", None),
    ] {
        let mut other = finding.clone();
        other["status"] = json!(status);
        assert_eq!(
            observation_from_finding(&other, &options).map(|i| i.action),
            action.map(str::to_owned),
            "{status}"
        );
    }
    let mut custom = options.clone();
    custom.actions.insert("drifted".into(), "rotate".into());
    assert_eq!(
        observation_from_finding(&finding, &custom).unwrap().action,
        "rotate"
    );
    let record = observer().record(input).unwrap();
    assert_eq!(record["changed_not_before"], "2026-01-01T00:00:00Z");
    assert!(record.get("changed_at").is_none());
}

fn executor() -> ExecutionRecorder {
    ExecutionRecorder::new("controller", "executor-1", &seed(12)).unwrap()
}

fn break_glass() -> BreakGlassInput {
    BreakGlassInput {
        execution_parameters: Some(json!({"version_id": "v7"})),
        ..BreakGlassInput::new(
            "kv:prod/api-key",
            "rotate",
            "secret.rotate",
            "incident 42: key leaked, NA unreachable",
            json!({"requested_capability": "secret.rotate"}),
            EvaluationFailure::NetworkError,
        )
    }
}

#[test]
fn a_break_glass_record_names_the_failed_request_by_digest_only() {
    let record = executor().sign_break_glass(break_glass()).unwrap();
    assert_eq!(
        record["evaluation_request_digest"],
        canonical_digest(&json!({"requested_capability": "secret.rotate"})).unwrap()
    );
    assert!(record.get("evaluation_request").is_none());
    assert!(record.get("attestation_id").is_none());
    assert_eq!(record["executor_sovereign_id"], "controller");
    assert_eq!(record["evaluation_failure"], "network_error");
    assert_eq!(record["outcome"], "success");
    assert_eq!(record["request_parameters"], json!({}));
    let key = [public_key_from_seed(&seed(12)).unwrap()];
    assert!(verify_out_of_band_record(&record, &key));
}

#[test]
fn a_break_glass_record_needs_a_justification_and_no_secret_material() {
    let recorder = executor();
    for justification in [String::new(), "x".repeat(1025)] {
        let input = BreakGlassInput {
            justification,
            ..break_glass()
        };
        assert_eq!(
            refusal(recorder.sign_break_glass(input).unwrap_err()),
            "break_glass_malformed"
        );
    }
    let longest = BreakGlassInput {
        justification: "é".repeat(1024),
        ..break_glass()
    };
    assert!(recorder.sign_break_glass(longest).is_ok());
    for input in [
        BreakGlassInput {
            execution_parameters: Some(json!({"client_secret": "x"})),
            ..break_glass()
        },
        BreakGlassInput {
            attributes: Some(json!({"token": "x"})),
            ..break_glass()
        },
        BreakGlassInput {
            outcome_detail: Some("-----BEGIN PRIVATE KEY-----".into()),
            ..break_glass()
        },
        BreakGlassInput {
            justification: "pasted -----BEGIN PRIVATE KEY----- by mistake".into(),
            ..break_glass()
        },
    ] {
        assert_eq!(
            refusal(recorder.sign_break_glass(input).unwrap_err()),
            "break_glass_secret_material"
        );
    }
}

// ── verify_evidence_events over records this test signs ─────────────────────

const NA: [u8; 32] = [21; 32];

fn na_key() -> String {
    public_key_from_seed(&seed(21)).unwrap()
}

fn sign_record(mut record: Value, key_id: &str, key: &SigningKey) -> Value {
    let canonical = out_of_band_canonical(&record).unwrap();
    record["signature"] = sign_canonical(&canonical, key_id, key);
    record
}

/// One export event after `prev`, with the envelope fields in `extra`.
fn event(seq: i64, kind: &str, payload: Value, prev: Option<&Value>, extra: Value) -> Value {
    let mut entry = json!({
        "store_sequence": seq, "entry_kind": kind, "recorded_at": "2026-01-01T00:10:00Z",
        "payload_digest": payload_digest(&payload).unwrap(),
        "prev_entry_digest": prev.map(|p| entry_digest(&p["entry"]).unwrap()),
        "decision_id": null, "context_id": null, "vendor_id": null, "attestation_id": null,
        "capability": null, "outcome": null, "evidence_id": null, "executor_sovereign_id": null,
        "exec_sequence_no": null, "resource_id": payload["resource_id"], "resource_action": null,
        "resource_sequence": null,
    });
    for (k, v) in extra.as_object().unwrap() {
        entry[k] = v.clone();
    }
    json!({"schema": "gm.evidence.event", "schema_version": 1, "entry_digest": entry_digest(&entry).unwrap(),
           "entry": entry, "payload": payload})
}

fn observed(id: &str, resource: &str) -> Value {
    let input = ObservationInput {
        observation_id: Some(id.into()),
        ..observation(resource, id)
    };
    observer().record(input).unwrap()
}

fn observer_keys() -> Vec<Value> {
    vec![json!({
        "key_id": "observer-1", "public_key": public_key_from_seed(&seed(11)).unwrap(),
        "executor_sovereign_id": "cloud-observer", "role": "observer",
    })]
}

/// Observations at `positions` for one resource, from store sequence `first`.
fn observations(first: i64, positions: &[i64], prev: Option<&Value>) -> Vec<Value> {
    let mut events: Vec<Value> = Vec::new();
    for (i, position) in positions.iter().enumerate() {
        let id = format!("obs-{first}-{i}");
        let before = events.last().or(prev).cloned();
        events.push(event(
            first + i as i64,
            "observation",
            observed(&id, "kv:v/s"),
            before.as_ref(),
            json!({"record_id": id, "observation_sequence": position}),
        ));
    }
    events
}

fn reasons(events: &[Value], options: &VerifyEvidenceOptions) -> Vec<String> {
    verify_evidence_events(events, options)
        .failures
        .into_iter()
        .map(|f| f.reason)
        .collect()
}

#[test]
fn observation_positions_are_checked_from_the_start_of_the_store_or_a_checkpoint() {
    let options = VerifyEvidenceOptions::new(vec![na_key()], observer_keys());
    let run = observations(1, &[1, 2], None);
    let result = verify_evidence_events(&run, &options);
    assert!(result.verified, "{result:?}");
    assert_eq!(result.observations, 2);
    assert_eq!(
        serde_json::to_value(&result).unwrap()["observations"],
        json!(2)
    );
    assert_eq!(
        reasons(&observations(1, &[1, 3], None), &options),
        ["observation_chain_break"]
    );
    assert_eq!(
        reasons(&observations(1, &[2], None), &options),
        ["observation_chain_break"]
    );
    // A run that does not start the store knows no earlier position.
    assert!(reasons(&observations(5, &[2, 3], None), &options).is_empty());
    assert_eq!(
        reasons(&observations(5, &[2, 4], None), &options),
        ["observation_chain_break"]
    );

    // A checkpoint carries the last removed position of each resource.
    let na = SigningKey::from_bytes(&NA);
    let removed = observations(1, &[1, 2, 3, 4], None);
    let mut checkpoint = json!({
        "checkpoint_id": "cp-1", "created_at": "2026-01-01T00:20:00Z", "cutoff": "2026-01-01T00:15:00Z",
        "removed_through_sequence": 4, "last_removed_entry_digest": entry_digest(&removed[3]["entry"]).unwrap(),
        "removed_count": 4, "previous_checkpoint_id": null, "issued_by": "na", "signature": null,
        "resource_heads": {}, "observation_heads": {"kv:v/s": 4},
    });
    checkpoint["signature"] =
        sign_canonical(&checkpoint_canonical(&checkpoint).unwrap(), "na", &na);
    let kept = |positions: &[i64]| observations(5, positions, Some(&removed[3]));
    let from = |checkpoint: &Value| VerifyEvidenceOptions {
        checkpoint: Some(checkpoint.clone()),
        ..VerifyEvidenceOptions::new(vec![na_key()], observer_keys())
    };
    assert!(reasons(&kept(&[5, 6]), &from(&checkpoint)).is_empty());
    assert_eq!(
        reasons(&kept(&[6]), &from(&checkpoint)),
        ["observation_chain_break"]
    );
    // A checkpoint without positions starts every resource at 1.
    let mut bare = checkpoint.clone();
    bare.as_object_mut().unwrap().remove("observation_heads");
    bare["signature"] = sign_canonical(&checkpoint_canonical(&bare).unwrap(), "na", &na);
    assert!(reasons(&kept(&[1]), &from(&bare)).is_empty());
    assert_eq!(
        reasons(&kept(&[5]), &from(&bare)),
        ["observation_chain_break"]
    );
}

#[test]
fn an_observation_verifies_only_under_an_observer_key_of_its_sovereign() {
    let run = observations(1, &[1], None);
    for (keys, verified) in [
        (observer_keys(), true),
        (
            vec![
                json!({"key_id": "observer-1", "public_key": public_key_from_seed(&seed(11)).unwrap(),
                        "executor_sovereign_id": "cloud-observer"}),
            ],
            false,
        ),
        (
            vec![
                json!({"key_id": "observer-1", "public_key": public_key_from_seed(&seed(11)).unwrap(),
                        "executor_sovereign_id": "other", "role": "observer"}),
            ],
            false,
        ),
    ] {
        let options = VerifyEvidenceOptions::new(vec![na_key()], keys);
        assert_eq!(verify_evidence_events(&run, &options).verified, verified);
    }
    // An envelope that names another record, or none (a null reads as absent).
    for record_id in [json!("other"), Value::Null] {
        let mut changed = observations(1, &[1], None);
        changed[0]["entry"]["record_id"] = record_id;
        changed[0]["entry_digest"] = json!(entry_digest(&changed[0]["entry"]).unwrap());
        let options = VerifyEvidenceOptions::new(vec![na_key()], observer_keys());
        assert_eq!(reasons(&changed, &options), ["envelope_mismatch"]);
    }
}

#[test]
fn an_execution_record_verifies_only_under_an_executor_key() {
    let v: Value = serde_json::from_str(include_str!("fixtures/python-vectors.json")).unwrap();
    let events = parse_export_lines(v["export"].as_str().unwrap()).unwrap();
    let keys = vec![v["na_public_key"].as_str().unwrap().to_owned()];
    let mut executor_keys = v["executor_keys"].as_array().unwrap().clone();
    let options = VerifyEvidenceOptions::new(keys.clone(), executor_keys.clone());
    let result = verify_evidence_events(&events, &options);
    assert!(result.verified, "{result:?}");
    // Counts of 1.3.0 kinds are left out of the JSON form when zero.
    let serialized = serde_json::to_value(&result).unwrap();
    assert!(COUNTS.iter().all(|k| serialized.get(*k).is_none()));
    executor_keys[0]["role"] = json!("observer");
    let observer = VerifyEvidenceOptions::new(keys, executor_keys);
    let result = verify_evidence_events(&events, &observer);
    assert!(result
        .failures
        .iter()
        .all(|f| f.reason == "invalid_signature" && f.detail == "execution"));
    assert_eq!(result.failures.len() as u64, result.executions);
}

fn judgement(id: &str, subject_id: &Value, digest: &Value, subject_sequence: i64) -> Value {
    let record = json!({
        "judgement_id": id, "subject_kind": "observation", "subject_id": subject_id,
        "subject_digest": digest, "subject_store_sequence": subject_sequence,
        "resource_id": "kv:v/s", "action": "rotate", "capability": "secret.rotate",
        "governed_by": "after_the_fact", "verdict": "deny", "evaluated_as_of": "2026-01-01T00:01:00Z",
        "gate_results": [], "judged_at": "2026-01-01T00:11:00Z", "issuer_sovereign_id": "na-sovereign",
        "issued_by": "na",
    });
    sign_record(record, "na", &SigningKey::from_bytes(&NA))
}

/// `observed`, then a judgement naming `subject_id` at `sequence`.
fn judged(observed: &[Value], subject_id: &Value, digest: &Value, sequence: i64) -> Vec<Value> {
    let last = observed.last().unwrap();
    let seq = last["entry"]["store_sequence"].as_i64().unwrap() + 1;
    let mut run = observed.to_vec();
    run.push(event(
        seq,
        "judgement",
        judgement("j-1", subject_id, digest, sequence),
        Some(last),
        json!({"record_id": "j-1", "subject_id": subject_id}),
    ));
    run
}

#[test]
fn a_judgement_names_its_record_as_stored() {
    let options = VerifyEvidenceOptions::new(vec![na_key()], observer_keys());
    let run = observations(1, &[1], None);
    let id = run[0]["payload"]["observation_id"].clone();
    let digest = run[0]["entry"]["payload_digest"].clone();
    let result = verify_evidence_events(&judged(&run, &id, &digest, 1), &options);
    assert!(result.verified, "{result:?}");
    assert_eq!((result.observations, result.judgements), (1, 1));
    assert_eq!(
        reasons(&judged(&run, &id, &digest, 3), &options),
        ["judgement_subject_mismatch"]
    );
    let other = json!("0".repeat(64));
    assert_eq!(
        reasons(&judged(&run, &id, &other, 1), &options),
        ["judgement_subject_mismatch"]
    );

    // A record a contiguous run should hold, but does not.
    let gone = judged(&run, &json!("obs-gone"), &digest, 1);
    assert_eq!(reasons(&gone, &options), ["judgement_subject_missing"]);
    let filtered = VerifyEvidenceOptions {
        contiguous: false,
        ..options.clone()
    };
    assert!(reasons(&gone, &filtered).is_empty());
    // A record before the run: removed by retention, or not exported.
    let later = observations(5, &[1], None);
    assert!(reasons(&judged(&later, &json!("obs-gone"), &digest, 2), &options).is_empty());
}

#[test]
fn a_quarantine_record_commits_to_the_record_it_holds() {
    let na = SigningKey::from_bytes(&NA);
    let held = json!({"evidence_id": "e-1", "outcome": "success"});
    let quarantine = |digest: String| {
        sign_record(
            json!({
                "quarantine_id": "q-1", "record_kind": "execution", "record": held,
                "record_digest": digest, "rejection_code": "evidence_decision_denied", "detail": "",
                "quarantined_at": "2026-01-01T00:11:00Z", "issuer_sovereign_id": "na-sovereign",
                "issued_by": "na",
            }),
            "na",
            &na,
        )
    };
    let options = VerifyEvidenceOptions::new(vec![na_key()], vec![]);
    let good = event(
        1,
        "quarantine",
        quarantine(payload_digest(&held).unwrap()),
        None,
        json!({"record_id": "q-1"}),
    );
    let result = verify_evidence_events(&[good], &options);
    assert!(result.verified, "{result:?}");
    assert_eq!(result.quarantined, 1);
    let bad = event(
        1,
        "quarantine",
        quarantine("0".repeat(64)),
        None,
        json!({"record_id": "q-1"}),
    );
    assert_eq!(reasons(&[bad], &options), ["quarantine_digest_mismatch"]);
}

#[test]
fn a_record_signed_with_a_non_utc_or_non_canonical_timestamp_does_not_verify() {
    let options = VerifyEvidenceOptions::new(vec![na_key()], observer_keys());
    let key = SigningKey::from_bytes(&[11; 32]);
    // Respelled after signing: the signature does not cover what was received.
    let mut respelled = observed("obs-x", "kv:v/s");
    respelled["observed_at"] = json!("2026-01-01T00:02:00+00:00");
    let run = vec![event(
        1,
        "observation",
        respelled.clone(),
        None,
        json!({"record_id": "obs-x", "observation_sequence": 1}),
    )];
    assert_eq!(reasons(&run, &options), ["invalid_signature"]);
    assert!(!verify_out_of_band_record(
        &respelled,
        &[public_key_from_seed(&seed(11)).unwrap()]
    ));
    for (field, value, reason) in [
        // Signed as received, but not the form the reference writes.
        (
            "observed_at",
            "2026-01-01T00:02:00+00:00",
            "non_canonical_form",
        ),
        (
            "observed_at",
            "2026-01-01T00:02:00.000000Z",
            "non_canonical_form",
        ),
        // The reference keeps these records' times in UTC.
        (
            "observed_at",
            "2026-01-01T01:02:00+01:00",
            "payload_invalid",
        ),
        ("observed_at", "2026-01-01T00:02:00", "payload_invalid"),
    ] {
        let mut record = observed("obs-x", "kv:v/s");
        record[field] = json!(value);
        let record = sign_record(record, "observer-1", &key);
        let run = vec![event(
            1,
            "observation",
            record,
            None,
            json!({"record_id": "obs-x", "observation_sequence": 1}),
        )];
        assert_eq!(reasons(&run, &options), [reason], "{value}");
    }
    let mut both = observed("obs-x", "kv:v/s");
    both["changed_not_before"] = json!("2026-01-01T00:00:00Z");
    both["changed_not_after"] = json!("2026-01-01T00:03:00Z");
    let both = sign_record(both, "observer-1", &key);
    let run = vec![event(
        1,
        "observation",
        both,
        None,
        json!({"record_id": "obs-x", "observation_sequence": 1}),
    )];
    assert_eq!(reasons(&run, &options), ["payload_invalid"]);
}
